export const CHANGEHOMEDATA='home/ChangeData'
export const ADDARTICLE='home/morearticle'
export const SCROLLSHOW='IfshwoScroll'
export const AUTHOR='getAuthors'
export const FOLLOW='changeFollow'
export const CHANGEAUTHORS='changeAuthorsPage'
